INSERT INTO company VALUES ('Renner-Schamberger','nCeYI3yq');
INSERT INTO company VALUES ('Abbott-Cronin','6QfN5QK');
INSERT INTO company VALUES ('Champlin, Koch and Paucek','hpa1MLyVnY5');
INSERT INTO company VALUES ('Rau-Rippin','NMR3U6');
INSERT INTO company VALUES ('Koss LLC','qK5PSB4uZ8u');
INSERT INTO company VALUES ('Roberts-Bosco','1201gZafpuaz');
INSERT INTO company VALUES ('Hartmann Inc','QkzXJVA');
INSERT INTO company VALUES ('Denesik, O''Keefe and Witting','CAdgAW');
INSERT INTO company VALUES ('Brakus Inc','c9kJN0wfHkcJ');
INSERT INTO company VALUES ('Ortiz Inc','yYdNFX');
INSERT INTO company VALUES ('Feil, Hudson and Rempel','IUocthQ');
INSERT INTO company VALUES ('Howe LLC','6AM4zdYV');
INSERT INTO company VALUES ('Wilderman and Sons','3zsMjqujAR');
INSERT INTO company VALUES ('White, Lehner and Hoppe','l14ZpBdIL3K');
INSERT INTO company VALUES ('Donnelly Inc','1mZAomD');
INSERT INTO company VALUES ('Bogan, Little and Kertzmann','LJ5KVh');
INSERT INTO company VALUES ('Bosco-Boyer','iL7njhYdrw');
INSERT INTO company VALUES ('Halvorson-Ryan','2lEr9yNGX');
INSERT INTO company VALUES ('Okuneva, Shanahan and Marvin','cS1wymCDI');
INSERT INTO company VALUES ('Daniel LLC','pLdY2y3pbqZ');
